(add-to-list 'load-path "~/emacs.d")

(load "00-init.el")
(load "10-package.el")
(load "10-editor.el")
(load "10-ui.el")
(load "20-cc.el")
(load "20-lisp.el")
;(load "20-nxml.el")
(load "20-org.el")
;(load "20-perl.el")
(load "20-python.el")
;(load "20-rst.el")
;(load "20-scala.el")
(load "20-sh.el")
(load "20-yasnippet.el")
(load "20-nxml.el")
(load "20-markdown.el")
(load "20-sql.el")
;(load "30-xcscope.el")
