(deftheme phenicsl-light "Light Theme by Phenicsl")

(let ((phenicsl-orange-1 "#D75A4F")
      (phenicsl-orange-2 "#D16040")
      (phenicsl-orange-3 "#DFAF8F")
      (phenicsl-blue-1 "#415591")
      (phenicsl-blue-2 "#4C708F")
      (phenicsl-blue-3 "#006799")
      (phenicsl-blue-4 "#4F608F")
      (phenicsl-blue-5 "#414E9E")
      (phenicsl-cyan-1 "#00A0A0")
      (phenicsl-cyan-2 "#24BDDF")
      (phenicsl-cyan-3 "#2481E1")
      (phenicsl-cyan-4 "#2481A6")
      (phenicsl-green-1 "#228B22")
      (phenicsl-green-2 "#228B57")
      (phenicsl-green-2 "#4F834F")
      (phenicsl-green-3 "#A8FF60")
      (phenicsl-green-4 "#99CC99")
      (phenicsl-green-5 "#DDFFDD")
      (phenicsl-green-7 "#41914F")
      (phenicsl-green-8 "#41874F")
      (phenicsl-green-9 "#418C4F")
      (phenicsl-gray-1 "#BFBFBF")
      (phenicsl-gray-2 "#F1F1F1")
      (phenicsl-gray-3 "#F2F2F2")
      (phenicsl-gray-4 "#FEFEFE")
      (phenicsl-gray-5 "#C1C1C1")
      (phenicsl-black-1 "#333333")
      (phenicsl-black-2 "#171717")
      (phenicsl-black-3 "#3F3F3F")
      (phenicsl-purple-1 "#9020C0")
      (phenicsl-purple-2 "#71405A")
      (phenicsl-purple-3 "#603C67")
      (phenicsl-purple-4 "#814F5A")
      (phenicsl-purple-4 "#91405F")
      (phenicsl-brown-1 "#8F3333")
      (phenicsl-red-1 "#AC7373")
      (phenicsl-red-2 "#AF5F77")
      (phenicsl-red-3 "#9C6363")
      (phenicsl-red-4 "#AC7171")
      (phenicsl-red-5 "#B22222")
      (phenicsl-red-6 "#FFDDDD")
      (phenicsl-red-7 "#BC5151")
      (phenicsl-yellow-1 "#FFFFB6")
      (builtin-color "#D16040")
      (comment-color "#BFBFBF")
      (constant-color "#4C708F")
      (function-color "#4C708F")
      (keyword-color "#71405A")
      (processor-color "#8F3333")
      (string-color "#AC5F5F")
      (type-color "#4F8C4F"))

  (custom-theme-set-faces
   'phenicsl-light
   ;; setup inheritance
   `(default ((t (:background "#FAFAFA" :foreground "#0F0F0F"))))
   `(fringe ((t  (:background "#F2F2F2"))))
   `(hl-line ((t (:background "#F2F2F2"))))
   `(region ((t (:background "#FFFFB6"))))
   '(cursor ((t (:background "#3A3A3A"))))
   ;`(font-lock-builtin-face ((t (:foreground "#D35A4F" :weight bold))))
   `(font-lock-builtin-face ((t (:foreground "#4F8C4F" :weight bold))))
   `(font-lock-comment-face ((t (:foreground "#C1C1C1"))))
   `(font-lock-comment-delimiter-face ((t (:foreground "#C1C1C1"))))
   `(font-lock-constant-face ((t (:foreground "#415591" :weight bold))))
   `(font-lock-function-name-face ((t (:foreground "#415591" :weight bold))))
   ; `(font-lock-keyword-face ((t (:foreground "#91405F" :weight bold))))
   ; `(font-lock-keyword-face ((t (:foreground "#4F8C4F" :weight bold))))
   `(font-lock-keyword-face ((t (:foreground "#BC5151" :weight bold))))
   ;`(font-lock-preprocessor-face ((t (:foreground "#8F3333" :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground "#AC5F5F" :weight bold))))   
   `(font-lock-string-face ((t (:foreground "#AC7171"))))
   `(font-lock-type-face ((t (:foreground  "#2481AF" :weight bold))))   
   `(font-lock-warning-face ((t (:foreground "#171717" :background "#FFFFB6"))))
   `(font-lock-variable-name-face ((t (:foreground "#171717"))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground "#4F834F" :weight bold))))
   `(font-lock-regexp-grouping-construct ((t (:foreground "#228B57" :weight bold))))
   `(font-lock-doc-face ((t (:foreground "#C1C1C1"))))

   `(linum ((t (:background "#3F3F3F" :foreground "#FFFFFF" :width expanded))))
   `(highlight ((t (:background "#FFFFB6"))))
   `(lazy-highlight ((t (:background "#FFFFB6"))))
   `(trailing-whitespace ((t (:background "#F2F2F2"))))

   `(rst-level-1-face ((t (:foreground "#415591" :weight bold :background nil))))
   `(rst-level-2-face ((t (:foreground "#2481AF" :weight bold :background nil))))
   `(rst-level-3-face ((t (:foreground "#D16040" :weight bold))))
   `(rst-level-4-face ((t (:foreground "#4F8C4F" :weight bold))))
   `(rst-level-5-face ((t (:foreground "#603C67" :weight bold))))
   `(rst-level-6-face ((t (:foreground "#AF5F77" :weight bold))))
   `(rst-block ((t (:foreground "#BC5151" :weight bold))))
   `(rst-external ((t (:foreground "#41914F" :weight bold))))
   
   `(org-level-1 ((t (:foreground "#415591" :weight bold))))
   `(org-level-2 ((t (:foreground "#2481AF" :weight bold))))
   `(org-level-3 ((t (:foreground "#D16040" :weight bold))))
   `(org-level-4 ((t (:foreground "#228B57" :weight bold))))
   `(org-level-7 ((t (:foreground "#603C67" :weight bold))))
   `(org-level-8 ((t (:foreground "#AF5F77" :weight bold))))
   `(org-table ((t (:foreground "#373737"))))
   `(org-date ((t (:foreground "#171717" :background "#FFFFB6"))))

   `(rainbow-delimiters-depth-1-face ((t (:foreground "#171717"))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground "#4C708F"))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground "#D16040"))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground "#228B57"))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground "#603C67"))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground "#AF5F77"))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground "#2481AF"))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground "#4F8C4F"))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground "#B22222"))))
   
   `(eshell-prompt ((t (:foreground "#8F3333" :weight bold))))
   `(eshell-ls-directory ((t (:foreground "#415591" :weight bold))))
   `(eshell-ls-executable ((t (:foreground "#4F8C4F"))))
   `(eshell-ls-symlink ((t (:foreground "#00A0A0"))))

   `(modeline ((t (:background "#3A3A3A" :foreground "#FFFFFF" :box nil))))
   `(modeline-highlight ((t (:background "#00A0A0" :box nil))))
   `(modeline-inactive ((t (:background "#4F4F4F" :foreground "#AAAAAA"))))
   `(modeline-buffer-id ((t (:background "#D16040" :foreground "#FFFFFF"))))
   `(modeline-mousable ((t (:background "#CCCCCC" :foreground "#FFFFFF"))))
   `(modeline-mousable-minor-mode ((t (:background "#CCCCCC" :foreground "#FFFFFF"))))
   
   `(sh-heredoc ((t (:foreground "#AC7171"))))
   `(sh-quoted-exec ((t (:foreground "#D35A4E"))))
   
   `(ido-subdir ((t (:foreground "#2481AF"))))
   `(ido-only-match ((t (:foreground "#4F8C4F"))))
   `(ido-indicator ((t (:foreground "#D16040" :background "#FFFFB6" :weight bold))))
   
   `(show-paren-match ((t (:weight bold))))
   `(show-paren-mismatch ((t (:background "#FFAAAA"))))
   `(minibuffer-prompt ((t (:foreground "#414E91" :weight bold))))
   `(yas/field-highlight-face ((t (:background "#FFFFB6" :foreground "#171717"))))
   `(info-node ((t (:foreground "#B22222" :slant italic :weight bold))))
   `(link ((t (:foreground "#414E91" :underline t :weight bold))))
   `(link-visited ((t (:foreground "#B22222" :weight bold))))))

