(deftheme phenicsl-dark "Private Theme by Phenicsl")


(let ((builtin-color "#FFC5AA")
      (comment-color "magenta")
      (constant-color "#99C9CC")
      (function-color "blue")
      (keyword-color "#FF875F")
      (preprocessor-color "#AFC4DB"))

  (custom-theme-set-faces
   'phenicsl-dark
   `(default ((t (:background "#303030" :foreground "#CCCCCC"))))
   `(fringe ((t  (:background "#3A3A3A" :foreground "#CCCCCC"))))
   `(hl-line ((t (:background "color-234"))))
   `(region ((t (:background "#D75F5F" :forground "white"))))
   `(font-lock-builtin-face ((t (:foreground "#FFC5AA"))))
   ;`(font-lock-comment-face ((t (:foreground "magenta"))))
   ;`(font-lock-comment-delimiter-face ((t (:foreground "magenta"))))
   `(font-lock-comment-face ((t (:foreground "#4C4C4C"))))
   `(font-lock-comment-delimiter-face ((t (:foreground "#4C4C4C"))))
   `(font-lock-constant-face ((t (:foreground "#99C9CC" :weight bold))))
   `(font-lock-function-name-face ((t (:foreground "#678FCC" :weight bold))))
   ;`(font-lock-function-name-face ((t (:foreground "#678FCC" :weight bold))))
   `(font-lock-function-name-face ((t (:foreground "#0000EE" :weight bold))))
   `(font-lock-keyword-face ((t (:foreground "#FF875F" :weight bold))))
   ;`(font-lock-keyword-face ((t (:foreground "#B294BB" :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground "#AFC4DB" :weight bold))))
   ;`(font-lock-string-face ((t (:foreground "#9CEE9C"))))
   `(font-lock-string-face ((t (:foreground "#B294BB"))))
   `(font-lock-type-face ((t (:foreground  "#68C1D8" :weight bold))))
   `(font-lock-variable-name-face ((t (:foreground "#FFFFFF"))))
   `(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "#C6A24F"))))
   `(font-lock-regexp-grouping-construct ((t (:inherit bold :foreground "#B18A3D"))))
   `(linum ((t (:background "#3A3A3A" :foreground "#8C8C8C"))))
   `(highlight ((t (:background "yellow" :foreground "black"))))
   `(lazy-highlight ((t (:background "yellow" :foreground "black"))))
   `(trailing-whitespace ((t (:background "#3C3C3C"))))
   `(rst-level-1-face ((t (:foreground "#0087ff" :weight bold :background nil))))
   `(rst-level-2-face ((t (:foreground "#00afff" :weight bold :background nil))))
   `(rst-level-3-face ((t (:foreground "#00ffff" :weight bold))))
   `(rst-level-4-face ((t (:foreground "#5fd75f" :weight bold))))
   `(rst-level-5-face ((t (:foreground "#603c67" :weight bold))))
   `(rst-level-6-face ((t (:foreground "#af5fff" :weight bold))))
   `(org-level-2 ((t (:foreground "#00FFFF" :weight bold))))
   `(org-level-4 ((t (:inherit outline-4 :weight bold))))
   `(org-level-7 ((t (:inherit outline-7 :weight bold))))
   `(org-level-8 ((t (:inherit outline-8 :weight bold))))
   `(org-table ((t (:foreground "#0087ff" :background nil))))
   `(org-date ((t (:foreground "#af5fff" :background nil))))
   `(modeline ((t (:background "#414141" :foreground "#AAAAAA"))))
   `(modeline-inactive ((t (:background "#3C3C3C" :foreground "#777777"))))
   `(modeline-buffer-id ((t (:background "#3C3C3C" :foreground "#FF875F"))))
   `(modeline-mousable ((t (:background "#999999" :foreground "black"))))
   `(modeline-mousable-minor-mode ((t (:background "#444444" :foreground "black"))))
   `(minibuffer-prompt ((t (:foreground "#0087ff"))))
   `(yas/field-highlight-face ((t (:background "#666666" :foreground "#ffff00"))))
   `(info-node ((t (:foreground "#FF875F" :slant italic :weight bold))))
   `(link ((t (:foreground "#00ffff" :underline t))))
   `(link-visited ((t (:foreground "magenta"))))))

